// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvmdjeblnitoskjqffbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2bWRqZWJsbml0b3NranFmZmJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjcxMDgsImV4cCI6MjA2OTA0MzEwOH0.SizTV9gNipqkeyKw8Mgqq3yDC6NFiYo3lGDWuKOl_8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});